development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://thmrioeyzyoqhi:ja5cKIKOh6C03YM1aj_0UWrNLD@ec2-184-73-202-229.compute-1.amazonaws.com:5432/d1fk7t0apucrsh